# Generated by Django 4.2.1 on 2023-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sova_market', '0003_alter_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Di', 'Директор'), ('AD', 'Администратор'), ('SM', 'Упаковщик'), ('CA', 'Кассир'), ('CL', 'Уборщик'), ('CR', 'Курьер')], default='CA', max_length=255),
        ),
    ]
